# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190302_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='shippingregion',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='shippingregion',
            name='modified_date',
        ),
    ]
