# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-02 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190302_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='product_id',
            new_name='product',
        ),
    ]
